### PR TITLE
Setup GitHub pages

### LINKED ISSUE #40: Publish to Github pages
Rename /dist folder to /docs to support Github Pages natively.

### PR DESCRIPTION
**Pull request by kdevnel**
closes #40 

This PR sets up the project and build processes to support Github Pages by default.

* The `/dist` folder is now `/docs` which is required for GH Pages to work
* `npm run build` should now bundle everything to the `/docs` folder automatically
* Updates the README.md file to be more user friendly for anyone wanting to just use the app from GH Pages without technical knowledge.

### CODE REVIEW

**Comment by kdevnel** [comment]
@bgrgicak I have decided against the GH action since Github Pages can automatically be generated from the /docs folder of any branch. Since the `main` branch should always be clean, I have opted to just use `/docs` instead of `/dist` for the production build process.

This should now automatically publish updates to the pages whenever I push an updated build to that folder for simplicity!

I think I will class this officially as version 1.0 - it is production-ready even though it could be improved! Let me know if you agree.

**Comment by bgrgicak** [comment]
Smart, this is a great solution 🚀 

I agree this looks great and no need to spend more time on it if you don't want to.

The only thing that I see that should improve is described in this issue https://github.com/kdevnel/ynab-absa-csv-convert-js/issues/44.

**Comment by kdevnel** [comment]
Thanks @bgrgicak I left a comment on that issue - I couldn't replicate 🤔

**Comment by bgrgicak** [comment]
It's fixed now :)

**Pull request merged**
