### PR TITLE
Adding unit testing with Jest

### LINKED ISSUE #48: Implement unit testing with Jest
This was mentioned in #20

### PR DESCRIPTION
**Pull request by kdevnel**
closes #48

## Description
Implements unit testing with Jest. Current implementation only tests the framework for testing by checking date conversion in the `modifyValues()` function.

## Testing
* Run `npm install` followed by `npm test` to run the test implemented

### CODE REVIEW

**Comment by kdevnel** [comment]
Hey @bgrgicak - could you help with some insight here?

Currently this PR is broken - the unit testing works when you run `npm test` but the other tasks such as `npm start` and `npm run build` no longer work.

Now, I've managed to narrow this down to adding `"type": "module",` to package.json on line 14 but this was required in order to allow Jest to recognise the module imports I was using. Now, by adding that it stops things working in the webpack config files.

If I remove that line, the build tasks work but the tests won't run due to a module error. I believe it's relating to how Jest doesn't yet fully support ES6 module exports. That's good to know but I don't really want to refactor the code just to accommodate Jest.

Do you have any thoughts or recommendations?

Here is the output when I run `npm start`:

[webpack-cli] Failed to load '/Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/webpack.dev.js' config
[webpack-cli] ReferenceError: require is not defined
    at file:///Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/webpack.dev.js:1:19
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async loadConfig (/Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/node_modules/webpack-cli/lib/webpack-cli.js:1351:35)
    at async /Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/node_modules/webpack-cli/lib/webpack-cli.js:1414:68
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig (/Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/node_modules/webpack-cli/lib/webpack-cli.js:1413:38)
    at async WebpackCLI.createCompiler (/Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/node_modules/webpack-cli/lib/webpack-cli.js:1837:22)
    at async Command.<anonymous> (/Users/a8c/repos/GitHub/ynab-absa-csv-convert-js/node_modules/@webpack-cli/serve/lib/index.js:81:30)
    at async Promise.all (index 1)

**Comment by bgrgicak** [comment]
@kdevnel [this fix worked for me](https://github.com/facebook/jest/issues/9395#issuecomment-583799300). Let me know if you want me to push it to this branch.

**Comment by kdevnel** [comment]
@bgrgicak that's perfect! I haven't tested it but if you could push it to this branch I will go ahead and test/merge as needed. Appreciate your input 😄

**Comment by kdevnel** [comment]
Looks good 🚀

**Pull request merged**
